---
version: '3'

volumes:
    mongo-volume: {}

services:
    database:
        image: mongo:4.4
        container_name: mongo
        environment: 
            - MONGO_INITDB_DATABASE=master # database name
            - MONGO_INITDB_ROOT_USERNAME=admin # root username
            - MONGO_INITDB_ROOT_PASSWORD=secret # root password
        volumes: 
            - ./mongo-volume:/data/db
        ports:
            - "127.0.0.1:27017-27019:27017-27019"
        expose:
            - "27017-27019"
    
    thavalon-db:
        container_name: thavalon-db
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
            - "127.0.0.1:8001:8001"
        volumes:
            - ./thavalon-db:/app
        expose:
            - "8001"
        depends_on: 
            - database